export const DETAILS_CREDITS_FAILED = 'DETAILS_CREDITS_FAILED'
export const DETAILS_CREDITS_REQUEST = 'DETAILS_CREDITS_REQUEST'
export const DETAILS_CREDITS_SUCCESS = 'DETAILS_CREDITS_SUCCESS'

export const DETAILS_IMAGES_FAILED = 'DETAILS_IMAGES_FAILED'
export const DETAILS_IMAGES_REQUEST = 'DETAILS_IMAGES_REQUEST'
export const DETAILS_IMAGES_SUCCESS = 'DETAILS_IMAGES_SUCCESS'

export const DETAILS_OVERVIEW_FAILED = 'DETAILS_OVERVIEW_FAILED'
export const DETAILS_OVERVIEW_REQUEST = 'DETAILS_OVERVIEW_REQUEST'
export const DETAILS_OVERVIEW_SUCCESS = 'DETAILS_OVERVIEW_SUCCESS'

export const DETAILS_RESET = 'DETAILS_RESET'

export const DETAILS_REVIEWS_FAILED = 'DETAILS_REVIEWS_FAILED'
export const DETAILS_REVIEWS_REQUEST = 'DETAILS_REVIEWS_REQUEST'
export const DETAILS_REVIEWS_SUCCESS = 'DETAILS_REVIEWS_SUCCESS'

export const DETAILS_VIDEOS_FAILED = 'DETAILS_VIDEOS_FAILED'
export const DETAILS_VIDEOS_REQUEST = 'DETAILS_VIDEOS_REQUEST'
export const DETAILS_VIDEOS_SUCCESS = 'DETAILS_VIDEOS_SUCCESS'
