export const MOVIE_INITIAL_FAILED = 'MOVIE_INITIAL_FAILED'
export const MOVIE_INITIAL_REQUEST = 'MOVIE_INITIAL_REQUEST'
export const MOVIE_INITIAL_SUCCESS = 'MOVIE_INITIAL_SUCCESS'

export const MOVIE_LOAD_BY_SCROLL_FAILED = 'MOVIE_LOAD_BY_SCROLL_FAILED'
export const MOVIE_LOAD_BY_SCROLL_REQUEST = 'MOVIE_LOAD_BY_SCROLL_REQUEST'
export const MOVIE_LOAD_BY_SCROLL_SUCCESS = 'MOVIE_LOAD_BY_SCROLL_SUCCESS'

export const MOVIE_LOAD_NEXT_FAILED = 'MOVIE_LOAD_NEXT_FAILED'
export const MOVIE_LOAD_NEXT_REQUEST = 'MOVIE_LOAD_NEXT_REQUEST'
export const MOVIE_LOAD_NEXT_SUCCESS = 'MOVIE_LOAD_NEXT_SUCCESS'

export const MOVIE_LOAD_PREV = 'MOVIE_LOAD_PREV'

export const MOVIE_TYPE = 'MOVIE_TYPE'
