export const SEARCH_QUERY_FAILED = 'SEARCH_QUERY_FAILED'
export const SEARCH_QUERY_REQUEST = 'SEARCH_QUERY_REQUEST'
export const SEARCH_QUERY_RESET = 'SEARCH_QUERY_RESET'
export const SEARCH_QUERY_SUCCESS = 'SEARCH_QUERY_SUCCESS'
